### ISSUE TITLE
Needs metadata.rb for internal supermarket upload

### ISSUE THREAD

**Issue by bridgetlane** [chef-cookbooks/chef-analytics#2]
Hello,
We're trying to upload this to our internal supermarket and it fails because it can't read metadata.json. It needs a metadata.rb, I've submitted a pull request with those changes here: https://github.com/chef-cookbooks/chef-analytics/pull/1
Let me know if you need any more information from me.

Thanks,

Bridget

**Comment by elliott-davis** [comment]
Closed by https://github.com/chef-cookbooks/chef-analytics/pull/1
