### ISSUE TITLE
Requires `accept_license` due to Chef MLSA

### ISSUE THREAD

**Issue by mengesb** [chef-cookbooks/chef-analytics#5]
### Cookbook version
0.2.0

### Chef-client version
12.8.1

### Platform Details
AWS CentOS 6.7 HVM w/Updates (x86_64)

### Scenario:
Install chef-analytics

### Steps to Reproduce:
Deploy using the following attributes:

```json
{
  "fqdn": "host.domain.tld",
  "chef-analytics": {
    "api_fqdn": "host.domain.tld",
    "version": "1.4.0"
  },
  "tags": []
}
```
### Expected Result:
chef-analytics should install on the host as a standalone server

### Actual Result:
error message prompting to accept the license during a reconfigure or pass `--accept-license`

### Notes:
This is a result of the following:
https://www.chef.io/blog/2016/04/26/changes-to-how-chef-products-handle-licenses/

**Comment by iennae** [comment]
Thanks for the contribution. I've merged and released the cookbook.
