### ISSUE TITLE
Error executing action `upgrade` on resource 'yum_package[analytics]'

### ISSUE THREAD

**Issue by apachewc** [chef-cookbooks/chef-analytics#7]
### Cookbook version
0.2.0

### Chef-client version
12.9.41

### Platform Details
RedHatEnterpriseServer 6.7

### Scenario:
Attempting 1st time install of Chef Analytics with this cookbook.

### Steps to Reproduce:
1. On Chef Server, edit /etc/opscode/chef-server.rb to include Analytics info & Rabbit MQ info per instructions here: https://docs.chef.io/install_analytics.html#standalone. Reconfigure & restart server and mgmt console. 
2. Copy files from /etc/opscode-analytics on Chef Server to target VM to be used for Chef Analytics. 
3. Place chef-analytics & chef-ingredient cookbooks in chef-repo. Update chef-analytics FQDN attribute to point to target VM. Upload to Chef Server. 
4. Bootstrap target VM. Add chef-analytics to run_list for target VM.
5. Run chef-client.

### Expected Result:
Expecting Chef Analytics to install. 

### Actual Result:
Chef-client run hits an error when attempting to upgrade (install) the analytics package. opscode-analytics-1.4.0-1.el6.x86_64.rpm did download to /var/chef/cache successfully. I've attached the chef-client run and chef-stacktrace.out

[chef-client analytics cookbook install issue 5-9-16.txt](https://github.com/chef-cookbooks/chef-analytics/files/257209/chef-client.analytics.cookbook.install.issue.5-9-16.txt)
[chef-stacktrace-out 5-9-16.txt](https://github.com/chef-cookbooks/chef-analytics/files/257208/chef-stacktrace-out.5-9-16.txt)

**Comment by binamov** [comment]
According to the linked txt files there may not be enough disk space in /opt to install Analytics @apachewc 

```
---- Begin output of rpm  -i /var/chef/cache/opscode-analytics-1.4.0-1.el6.x86_64.rpm ----
STDOUT: 
STDERR: warning: /var/chef/cache/opscode-analytics-1.4.0-1.el6.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
        installing package opscode-analytics-1.4.0-1.el6.x86_64 needs 164MB on the /opt filesystem
---- End output of rpm  -i /var/chef/cache/opscode-analytics-1.4.0-1.el6.x86_64.rpm ----
```

**Comment by mengesb** [comment]
@binamov - it may not seem obvious, but that error means you're out of file system space to install the package. This isn't a cookbook issue.

**Comment by mengesb** [comment]
@apachewc, @binamov is correct; that's exactly what this means (I was caught with this issue during other development). Be sure your VM has a large enough disk or /opt partition.

**Comment by apachewc** [comment]
Ah, thank you for catching that... was looking in all the wrong places for the issue. I will retry and close this out if successful.
