### ISSUE TITLE
action :upgrade incompatible with version property

### ISSUE THREAD

**Issue by haidangwa** [chef-cookbooks/chef-analytics#9]
### Cookbook version

0.2.0
### Chef-client version

12.11.18
### Platform Details

RHEL6
### Scenario:

I've specified exactly version 1.4.0 of chef-analytics. However, the recipe uses the `:upgrade` action; thus, ignoring any value of `version`. See https://github.com/chef-cookbooks/chef-analytics/blob/master/recipes/default.rb#L22
### Steps to Reproduce:

I created a wrapper cookbook and set `node.default['chef-analytics']['version'] = '1.4.0'`
### Expected Result:

chef-analytics 1.4.0 is installed
### Actual Result:

chef-analytics 1.5.0 is installed, because that is currently the latest version of chef-analytics. This behavior is consistent with the yum_package or package resources in chef.

**Comment by tas50** [comment]
Fixed in master
